package goAuth

// LOG PATH
// var GOAUTH_LOG_PATH string = "GOAUTH_LOG_PATH"

// SECRET KEY
var GOAUTH_JWT_SECRET_KEY string = "GOAUTH_JWT_SECRET_KEY"

// certificate path
var GOAUTH_CERT_ENABLED = "GOAUTH_CERT_ENABLED"
var GOAUTH_CERT_PATH = "GOAUTH_CERT_PATH"
var GOAUTH_CERT_KEY = "GOAUTH_CERT_KEY"
